# 1. SSM Discovery Variables
variable "network_ssm_prefix" {
  description = "The prefix used in SSM to find VPC/Subnet IDs (e.g., /infra/stage)"
  type        = string
}

# 2. DNS Variables
variable "app_subdomain" {
  description = "The full domain name for this specific app (e.g., crm-stage.example.com)"
  type        = string
}

# 3. CloudFront Inputs (Passed from the Compute Module)
variable "cloudfront_domain_name" {
  description = "The d123.cloudfront.net endpoint generated by the compute module"
  type        = string
}

variable "cloudfront_hosted_zone_id" {
  description = "The static Hosted Zone ID for CloudFront (always Z2FDTNDATAQYW2)"
  type        = string
  default     = "Z2FDTNDATAQYW2" # This is a global AWS constant for CloudFront
}

# 4. General Metadata
variable "environment" {
  description = "The environment name (dev/stage/prod)"
  type        = string
}

variable "app_name" {
  description = "The name of the BPO application (crm/inventory/hr/billing)"
  type        = string
}