name: App Infrastructure Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'modules/**'
      - 'environments/dev/ecommerce/**'
      - 'environments/dev/crm/**'
      - 'environments/dev/web/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'modules/**'
      - 'environments/dev/ecommerce/**'
      - 'environments/dev/crm/**'
      - 'environments/dev/web/**'
      - 'environments/dev/ciam/**'

jobs:
  # This job determines which apps need to be updated
  changes:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            ecommerce: 
              - 'modules/**'
              - 'environments/dev/ecommerce/**'
            crm: 
              - 'modules/**'
              - 'environments/dev/crm/**'
            web: 
              - 'modules/**'
              - 'environments/dev/web/**'
            ciam: 
              - 'modules/**'
              - 'environments/dev/ciam/**'

  terraform:
    needs: changes
    if: ${{ needs.changes.outputs.apps != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # This will only run for the apps that detected changes above
        app: ${{ fromJSON(needs.changes.outputs.apps) }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Plan
        env:
          # Mapping the matrix names to your actual directory paths
          APP_PATH: "environments/dev/${{ matrix.app }}"
        run: |
          cd $APP_PATH
          terraform init
          terraform plan -no-color
