name: App Infrastructure Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'modules/**'
      - 'environments/dev/ecommerce/**'
      - 'environments/dev/crm/**'
      - 'environments/dev/web/**'
      - 'environments/dev/ciam/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'modules/**'
      - 'environments/dev/ecommerce/**'
      - 'environments/dev/crm/**'
      - 'environments/dev/web/**'
      - 'environments/dev/ciam/**'

jobs:
  # STEP 1: Detect which folders changed
  changes:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            ecommerce: 
              - 'modules/**'
              - 'environments/dev/ecommerce/**'
            crm: 
              - 'modules/**'
              - 'environments/dev/crm/**'
            web: 
              - 'modules/**'
              - 'environments/dev/web/**'
            ciam: 
              - 'modules/**'
              - 'environments/dev/ciam/**'

  # STEP 2: Run Terraform for each changed app
  terraform:
    needs: changes
    if: ${{ needs.changes.outputs.apps != '[]' && needs.changes.outputs.apps != '' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: ${{ fromJSON(needs.changes.outputs.apps) }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Create AWS Profile
        run: |
          mkdir -p ~/.aws
          
          # Create the Config file (Note the 'profile' prefix)
          cat <<EOF > ~/.aws/config
          [profile secondary-account]
          region = ap-southeast-1
          output = json
          EOF

          # Create the Credentials file (Note: NO 'profile' prefix here)
          cat <<EOF > ~/.aws/credentials
          [secondary-account]
          aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EOF

      - name: Terraform Init & Plan
        env:
          APP_PATH: "environments/dev/${{ matrix.app }}"
          # We unset these to force Terraform to look at our created profile
          AWS_ACCESS_KEY_ID: ""
          AWS_SECRET_ACCESS_KEY: ""
        run: |
          if [ -d "$APP_PATH" ]; then
            echo "Changing directory to $APP_PATH"
            cd $APP_PATH
          
            # Using -reconfigure to force a fresh backend check with the new profile
            terraform init -reconfigure
            terraform plan -no-color
          else
            echo "Directory $APP_PATH not found. Skipping."
            exit 1
          fi